{% set name = "snakemake-wrapper-utils" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 13b13b65d3eb62488e6e56ff65fecf825fbbaa4eb773b97c64558aa33d5277cb

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - snakemake_wrapper_utils

about:
  home: https://github.com/snakemake/snakemake-wrapper-utils
  license: MIT
  license_file: LICENSE.md
  summary: "A collection of utility functions and classes for Snakemake wrappers."

extra:
  recipe-maintainers:
    - johanneskoester
