{% set name = "shasta" %}
{% set version = "0.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

# source:
#   url: https://github.com/chanzuckerberg/{{ name }}/archive/{{ version }}.tar.gz
#   sha256: a05da3b18d68abade48dcab5e6a49471880f004b75ac803d6fe704e6aa841dc6
#   folder: shasta
source:
  url: https://github.com/chanzuckerberg/shasta/releases/download/0.6.0/shasta-Linux-0.6.0 # [linux]
  sha256: 72d5be2135de3b10d80022e30925a6b68a442615a8d5e333fc4a2845db509666 # [linux]
  url: https://github.com/chanzuckerberg/shasta/releases/download/0.6.0/shasta-macOS-0.6.0 # [osx]
  sha256: aab24adcbcf42433b3a69261cf9d517f05c20f21f835d092546ff835cabe6320 # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
  run:
    - libpng


test:
  imports:
    - shasta
  commands:
    - shasta --help

about:
  home: https://github.com/chanzuckerberg/shasta
  license: MIT
  license_file: LICENSE
  summary: rapidly produce accurate assembled sequence using as input DNA reads generated by Oxford Nanopore flow cells.
  doc_url: https://chanzuckerberg.github.io/shasta/index.html
  dev_url: https://github.com/chanzuckerberg/shasta
