{% set name = "helen" %}
{% set version = "0.0.23" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e59fa207667f1d610dd6f768e8536cc0568a274dd4f7b0df841ee2e4f3e50457

build:
  number: 0
  entry_points:
    - helen = helen.helen:main
    - helen_train = helen.helen_train:main
    - marginpolish = helen.marginpolish:main
    - marginPolish = helen.marginpolish:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - h5py
    - hyperopt
    - matplotlib
    - numpy
    - onnx
    - onnxruntime
    - pip
    - python
    - pyyaml
    - torch
    - torchnet
    - torchvision
    - tqdm
    - wget
  run:
    - h5py
    - hyperopt
    - matplotlib
    - numpy
    - onnx
    - onnxruntime
    - python
    - pyyaml
    - torch
    - torchnet
    - torchvision
    - tqdm
    - wget

test:
  imports:
    - helen/
    - helen/modules/python
    - helen/modules/python/helper
    - helen/modules/python/models
  commands:
    - helen --help
    - helen_train --help
    - marginpolish --help
    - marginPolish --help

about:
  home: "https://github.com/kishwarshafin/helen"
  license: MIT
  license_file: LICENSE
  summary: "RNN based assembly HELEN. It works paired with MarginPolish."